config/routes.rb
Rails.application.routes.draw do
  resources :perros
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/perro.rb
class Perro < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/perros_controller.rb
class PerrosController < ApplicationController
  before_action :set_perro, only: %i[ show edit update destroy ]

  # GET /perros or /perros.json
  def index
    @perros = Perro.all
  end

  # GET /perros/1 or /perros/1.json
  def show
  end

  # GET /perros/new
  def new
    @perro = Perro.new
  end

  # GET /perros/1/edit
  def edit
  end

  # POST /perros or /perros.json
  def create
    @perro = Perro.new(perro_params)

    respond_to do |format|
      if @perro.save
        format.html { redirect_to perro_url(@perro), notice: "Perro was successfully created." }
        format.json { render :show, status: :created, location: @perro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @perro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /perros/1 or /perros/1.json
  def update
    respond_to do |format|
      if @perro.update(perro_params)
        format.html { redirect_to perro_url(@perro), notice: "Perro was successfully updated." }
        format.json { render :show, status: :ok, location: @perro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @perro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /perros/1 or /perros/1.json
  def destroy
    @perro.destroy

    respond_to do |format|
      format.html { redirect_to perros_url, notice: "Perro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perro
      @perro = Perro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def perro_params
      params.require(:perro).permit(:name, :breed, :owner, :age, :weight, :birth_date, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :surname, :dni, :mail, :address, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/perros_helper.rb
module PerrosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tu Proyecto</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", alt: "Logo", height: "30" %>
    <% end %>

    <div class="navbar-collapse collapse justify-content-center">
      <span class="navbar-text">
        Tu Eslogan
      </span>
    </div>

    <div class="navbar-collapse collapse justify-content-end">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Iniciar sesión", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Registrarse", signup_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </nav>

  <div class="container">
    <h1>Bienvenido a tu Proyecto</h1>
    <!-- Aquí puedes agregar el contenido de tu página de inicio -->
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ohmydog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/perros/_form.html.erb
<%= form_with(model: perro) do |form| %>
  <% if perro.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(perro.errors.count, "error") %> prohibited this perro from being saved:</h2>

      <ul>
        <% perro.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :breed, style: "display: block" %>
    <%= form.text_field :breed %>
  </div>

  <div>
    <%= form.label :owner, style: "display: block" %>
    <%= form.text_field :owner %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.text_field :age %>
  </div>

  <div>
    <%= form.label :weight, style: "display: block" %>
    <%= form.text_field :weight %>
  </div>

  <div>
    <%= form.label :birth_date, style: "display: block" %>
    <%= form.date_field :birth_date %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/perros/_perro.html.erb
<div id="<%= dom_id perro %>">
  <p>
    <strong>Name:</strong>
    <%= perro.name %>
  </p>

  <p>
    <strong>Breed:</strong>
    <%= perro.breed %>
  </p>

  <p>
    <strong>Owner:</strong>
    <%= perro.owner %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= perro.age %>
  </p>

  <p>
    <strong>Weight:</strong>
    <%= perro.weight %>
  </p>

  <p>
    <strong>Birth date:</strong>
    <%= perro.birth_date %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= perro.image %>
  </p>

</div>

app/views/perros/edit.html.erb
<h1>Editing perro</h1>

<%= render "form", perro: @perro %>

<br>

<div>
  <%= link_to "Show this perro", @perro %> |
  <%= link_to "Back to perros", perros_path %>
</div>

app/views/perros/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Perros</h1>

<div id="perros">
  <% @perros.each do |perro| %>
    <%= render perro %>
    <p>
      <%= link_to "Show this perro", perro %>
    </p>
  <% end %>
</div>

<%= link_to "New perro", new_perro_path %>

app/views/perros/new.html.erb
<h1>New perro</h1>

<%= render "form", perro: @perro %>

<br>

<div>
  <%= link_to "Back to perros", perros_path %>
</div>

app/views/perros/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @perro %>

<div>
  <%= link_to "Edit this perro", edit_perro_path(@perro) %> |
  <%= link_to "Back to perros", perros_path %>

  <%= button_to "Destroy this perro", @perro, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
<<<<<<< HEAD
    <%= form.text_field :name, required: true %>
=======
    <%= form.text_field :name %>
>>>>>>> 9f85fa01c26c793749661f039ac086d27f2ff338
  </div>

  <div>
    <%= form.label :surname, style: "display: block" %>
<<<<<<< HEAD
    <%= form.text_field :surname, required: true %>
=======
    <%= form.text_field :surname %>
>>>>>>> 9f85fa01c26c793749661f039ac086d27f2ff338
  </div>

  <div>
    <%= form.label :dni, style: "display: block" %>
<<<<<<< HEAD
    <%= form.text_field :dni, required: true%>
=======
    <%= form.text_field :dni %>
>>>>>>> 9f85fa01c26c793749661f039ac086d27f2ff338
  </div>

  <div>
    <%= form.label :mail, style: "display: block" %>
<<<<<<< HEAD
    <%= form.text_field :mail, required: true %>
=======
    <%= form.text_field :mail %>
>>>>>>> 9f85fa01c26c793749661f039ac086d27f2ff338
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
<<<<<<< HEAD
    <%= form.text_field :address, required: true %>
=======
    <%= form.text_field :address %>
>>>>>>> 9f85fa01c26c793749661f039ac086d27f2ff338
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
<<<<<<< HEAD
    <%= form.text_field :phone, required: true %>
  </div>

    <div>
      <%= form.label :dog_name, style: "display: block" %>
      <%= form.text_field :dog_name, required: true %>
=======
    <%= form.text_field :phone %>
>>>>>>> 9f85fa01c26c793749661f039ac086d27f2ff338
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
<<<<<<< HEAD

<style>
  .error-message {
    display: flex;
    align-items: center;
    color: #FF6600;
    background-color: #FFF3E8;
    padding: 10px;
    border-radius: 5px;
    margin-bottom: 10px;
  }

  .error-message img {
    width: 24px;
    height: 24px;
    margin-right: 10px;
  }
</style>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    var form = document.getElementById('signin-form');

    form.addEventListener('submit', function(event) {
      event.preventDefault();

      var nameInput = document.getElementById('user_name');
      var surnameInput = document.getElementById('user_surname');
      var passwordInput = document.getElementById('user_password');
      var mailInput = document.getElementById('user_mail');
      var phoneInput = document.getElementById('user_phone');
      var dniInput = document.getElementById('user_dni');
      var dogNameInput = document.getElementById('user_dog_name');

      // Validate name
      if (nameInput.value === '') {
        alert('Por favor, ingrese su nombre.');
        return false;
      }

      // Validate surname
      if (nameInput.value === '') {
        alert('Por favor, ingrese su apellido.');
        return false;
      }

      // Validate password
      if (passwordInput.value === '') {
        alert('Por favor, ingrese una contraseña.');
        return false;
      }

      // Validate email
      var emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(emailInput.value)) {
        alert('Por favor, ingrese una direcciòn email vàlida.');
        return false;
      }

      // Validate phone number
      var phoneRegex = /^\d{10}$/;
      if (!phoneRegex.test(phoneInput.value)) {
        alert('Por favor, ingrese un nùmero vàlido de 10 dìgitos.');
        return false;
      }

      // Validate ID
      if (idInput.value.length < 7) {
        alert('Por favor, inserte un DNI correcto.');
        return false;
      }

      // Validate dog's name
      if (dogNameInput.value === '') {
        alert('Por favor, ingrese el nombre de su perro.');
        return false;
      }

      // Form is valid, proceed with submission
      form.submit();
    });
  });

function displayError(message) {
  var errorContainer = document.createElement('div');
  errorContainer.className = 'error-message';

  var errorLogo = document.createElement('img');
  errorLogo.src = '/path/to/error-logo.png'; // Replace with the correct path to your error logo image

  var errorMessage = document.createElement('span');
  errorMessage.textContent = message;

  errorContainer.appendChild(errorLogo);
  errorContainer.appendChild(errorMessage);

  var form = document.getElementById('signin-form');
  form.insertBefore(errorContainer, form.firstChild);
}

</script>
=======
>>>>>>> 9f85fa01c26c793749661f039ac086d27f2ff338

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Surname:</strong>
    <%= user.surname %>
  </p>

  <p>
    <strong>Dni:</strong>
    <%= user.dni %>
  </p>

  <p>
    <strong>Mail:</strong>
    <%= user.mail %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= user.address %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= user.phone %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>